/**
 * Barcode Service
 * Handles barcode generation and PDF creation for visitor passes
 */
import JsBarcode from 'jsbarcode';
import { jsPDF } from 'jspdf';

class BarcodeGenerator {
  /**
   * Generate a barcode image as a data URL
   * @param {string} text - The text to encode in the barcode
   * @returns {string} - Base64 data URL of the barcode image
   */
  static generateBarcode(text) {
    const canvas = document.createElement('canvas');
    JsBarcode(canvas, text, {
      format: 'CODE128',
      width: 2,
      height: 100,
      displayValue: true
    });
    return canvas.toDataURL();
  }

  /**
   * Generate a printable PDF visitor pass with barcode
   * @param {string} plateNumber - Vehicle plate number
   * @param {string} barcodeData - Data to encode in barcode
   * @param {string} expiresAt - Expiration datetime string
   * @returns {jsPDF} - The generated PDF document
   */
  static generatePDF(plateNumber, barcodeData, expiresAt) {
    const pdf = new jsPDF();
    
    // Add header
    pdf.setFontSize(16);
    pdf.text('DA Vehicle Gate Pass System', 20, 20);
    pdf.setFontSize(12);
    pdf.text('Department of Agriculture Region V', 20, 30);
    
    // Add vehicle info
    pdf.setFontSize(14);
    pdf.text(`Plate Number: ${plateNumber}`, 20, 50);
    pdf.text(`Expires: ${new Date(expiresAt).toLocaleDateString()}`, 20, 60);
    
    // Generate barcode
    const canvas = document.createElement('canvas');
    JsBarcode(canvas, barcodeData, {
      format: 'CODE128',
      width: 3,
      height: 80,
      displayValue: true
    });
    
    // Add barcode to PDF
    const barcodeImage = canvas.toDataURL();
    pdf.addImage(barcodeImage, 'PNG', 20, 70, 150, 40);
    
    // Add footer
    pdf.setFontSize(10);
    pdf.text('Generated by DA Vehicle Gate Pass System', 20, 120);
    
    return pdf;
  }
}

export default BarcodeGenerator;
